### ISSUE TITLE
[バグ]v0.3.0のコメント取得数が少ない？

### ISSUE THREAD

**Issue by T-10001** [Hayao-H/Niconicome#142]
**バグの説明**
v0.3.0のコメント取得数が少ない。

**再現方法**
例えば動画so14164307に使うとたった3400/58079件のコメントが取得される。v0.2.5.24323を`offset=200`で使うと57508件のコメントが取得される。

**期待する挙動**
v0.2.5.24323のコメント取得数と同じ数かそれ以上のコメントを取得する。

**スクリーンショット**
可能であれば

**Desktop (下記の情報の記載をお願いします):**
 - OS: Windows 10 Pro 19042.746 64bit
 - Version: v0.3.0 release

**ログファイル**
可能であれば添付して下さい

**備考**
その他

**Comment by Hayao-H** [comment]
申し訳ありません
現在原因を確認中です

**Comment by Hayao-H** [comment]
修正しました。
現在``develop``に``push``が完了しました。
