### ISSUE TITLE
[バグ] ログアウトせずにniconicomeを終了後、再度起動するとログイン状態は保持されているがユーザーネームが『未ログイン』となる

### ISSUE THREAD

**Issue by Ugya** [Hayao-H/Niconicome#244]
**バグの説明**
niconicomeをログアウトせずに✕等で終了し、再度niconicomeを起動するとユーザーネームが『未ログイン』となる
※プレミアムユーザー及び二段ログインによりブラウザでログインを使用するを利用

**期待する挙動**
ブラウザログイン時でのログイン保持状態時にniconicomeを起動しユーザーネームを確認すると自身のユーザーネームが表示される

**スクリーンショット**
https://i.imgur.com/eCdbLb3.png

**Desktop (下記の情報の記載をお願いします):**
 - OS:  Windows 10 Pro x64 21H1 19043.985
 - Version: 0.3.x以降

**Comment by Hayao-H** [comment]
ご報告ありがとうございます
問題を確認しました
