### ISSUE TITLE
[新機能]360px設定で600kbbsをダウンロードするように

### ISSUE THREAD

**Issue by maru211** [Hayao-H/Niconicome#247]
優先解像度360px設定でDLすると0.3.0では600kbbsだったのですが、
今のバージョンでは300kbbsの方をDLするようです。
600kbbsの方をDLするかどちらか選択できるようにしてもらえないでしょうか？

**Comment by Hayao-H** [comment]
よろしければ動画IDを教えていただけますか？

**Comment by maru211** [comment]
0.4.0、0.5.0は全ての動画で300kbbsになります。
同じ動画でも0.3.0なら600kbbsの方がダウンロードできます。

**Comment by Hayao-H** [comment]
ありがとうございます

**Comment by Hayao-H** [comment]
[ この行](https://github.com/Hayao-H/Niconicome/blob/5ec3efabd8319543a2778f4ccb3c58c2f4eeb7fb/Niconicome/Models/Domain/Niconico/Dmc/StreamsCollection.cs#L67)と[この行](https://github.com/Hayao-H/Niconicome/blob/5ec3efabd8319543a2778f4ccb3c58c2f4eeb7fb/Niconicome/Models/Domain/Niconico/Dmc/StreamsCollection.cs#L87)の
```c#
if (preferLowBitrate){
}
```
を
```c#
if (!preferLowBitrate){
}
```
に変える
