### ISSUE TITLE
[バグ]UTF-8でエンコードされているXMLファイルがUTF-16のふりをしている

### ISSUE THREAD

**Issue by hts-ozeki** [Hayao-H/Niconicome#308]
**バグの説明**
UTF-8でエンコードされているXMLファイルに、
`<?xml version="1.0" encoding="utf-16"?>`と書いている。

**再現方法**
動画情報ファイルの保存形式をXMLにして動画をダウンロードしました。

**期待する挙動**
`<?xml version="1.0" encoding="utf-8"?>`と書くべき。

**Desktop (下記の情報の記載をお願いします):**
 - OS:  Windows 10 Pro 64bit 20H2 build 19042.985
 - Windows Feature Experience Pack: 120.2212.2020.0
 - Version: 0.6.2

**Comment by Hayao-H** [comment]
ご報告ありがとうございます
問題を確認しました
