### ISSUE TITLE
[バグ]すべての過去ログをDL出来ない

### ISSUE THREAD

**Issue by Hayao-H** [Hayao-H/Niconicome#313]
**バグの説明**
明確な状況・バグの説明

**再現方法**
検証用の動画IDでも結構です

**期待する挙動**
本来ならばどのような挙動が望ましいのか

**スクリーンショット**
可能であれば

**Desktop (下記の情報の記載をお願いします):**
 - OS:  最低限OSバージョン・64bitか32bitかなどをお願いします
 - Version: アプリケーションのバージョン

**ログファイル**
可能であれば添付して下さい

**備考**
その他

**Comment by Hayao-H** [comment]
- ``content``のところを毎分設定ではなくトータルコメ数にする

**Comment by T-10001** [comment]
v0.7.1からv0.9までもすべての過去ログをDL出来なかった事がありました。
so37903088が5065/16214件しかDLしません。
so37696196が3307/18886件しかDLしません。

[魔女の旅々 第10話「二人の師匠」 so37903088 2021-08-31 17-49-45 [].txt](https://github.com/Hayao-H/Niconicome/files/7090167/10.so37903088.2021-08-31.17-49-45.txt)
[ひぐらしのなく頃に業 第3話「鬼騙し編　其の参」 so37696196 2021-08-21 19-53-35 [].txt](https://github.com/Hayao-H/Niconicome/files/7090168/3.so37696196.2021-08-21.19-53-35.txt)

**Comment by Hayao-H** [comment]
ご報告ありがとうございます。
問題を確認しました。

**Comment by T-10001** [comment]
この問題が修正されたと聞きました。しかし、v0.10.0で「試験的なコメント...」を有効にしても、so37738757のコメントDLに2500/3104しか取得できませんでした。昔のDLだと全3104を取得できました。

[キミと僕の最後の戦場、あるいは世界が始まる聖戦 第4話「交差　―ボルテックス攻防―」 so37738757 2021-07-03 19-29-10 [].txt](https://github.com/Hayao-H/Niconicome/files/7273077/4.so37738757.2021-07-03.19-29-10.txt)
[キミと僕の最後の戦場、あるいは世界が始まる聖戦 第4話「交差　―ボルテックス攻防―」 so37738757 [ 2340 ] 2021-10-03 20-23-00 [].txt](https://github.com/Hayao-H/Niconicome/files/7273078/4.so37738757.2340.2021-10-03.20-23-00.txt)

**Comment by T-10001** [comment]
v0.11.1では「コメントの取りこぼしを最小限にするように設計したコメント取得システムをご利用可能です」とかかれていましたが、sm11949840 で試したところ、たった501／9,264のコメントしかダウンロードできませんでした。

「設定＞ダウンロード設定＞試験的なコメント取得システムを有効にする」にチェックはありました。
