### ISSUE TITLE
[バグ] 起動時に実行ファイルがあるディレクトリにchromeディレクトリがないとエラーが発生する

### ISSUE THREAD

**Issue by sh4869221b** [Hayao-H/Niconicome#353]
**バグの説明**
起動時に実行ファイルがあるディレクトリにchromeディレクトリがないとエラーが発生する

**再現方法**
**期待する挙動**
本来ならばどのような挙動が望ましいのか

**スクリーンショット**
可能であれば

**Desktop (下記の情報の記載をお願いします):**
 - OS:  最低限OSバージョン・64bitか32bitかなどをお願いします
 - Version: アプリケーションのバージョン

**ログファイル**
https://gist.githubusercontent.com/sh4869221b/4b23d46c1d9fecdbb287914d04645057/raw/8a5dced74e49027698ecb31f07e3399d436bd38c/niconicome-log

**備考**
その他

**Comment by Hayao-H** [comment]
ご報告ありがとうございます。
問題を確認しました。
