### ISSUE TITLE
[バグ] 一時プレイリストの全動画のダウンロード状態が同じ

### ISSUE THREAD

**Issue by T-10001** [Hayao-H/Niconicome#361]
**バグの説明**
明確な状況・バグの説明
全動画のダウンロード状態が同じ

**再現方法**
検証用の動画IDでも結構です

**期待する挙動**
本来ならばどのような挙動が望ましいのか

**スクリーンショット**
![image](https://user-images.githubusercontent.com/20717627/127076601-ad86760a-67d3-49c2-bfe4-90b2ea669bdb.png)

**Desktop (下記の情報の記載をお願いします):**
 - OS:  Windows 10 Pro 20H2 19042.1110
 - Version: 0.7.1.22038

**ログファイル**
可能であれば添付して下さい

**備考**
その他

**Comment by Hayao-H** [comment]
ご報告ありがとうございます。
すべて別の動画ですか？

**Comment by T-10001** [comment]
はい。全部同じチャネルからの動画ですけれど。更に一行のチェックボックスを選択しても全行がチェックされます。

**Comment by Hayao-H** [comment]
試しに[小林さんちのメイドラゴンS](https://ch.nicovideo.jp/maidragon_S)をチャンネルとして登録してから、全話のDLを試行しましたが、期待通りの挙動（無料公開中の最新話(EP4)と常設無料のEP1は成功、ほかは失敗）という結果になりました。
チャンネル名を教えていただくことはできますか？

**Comment by T-10001** [comment]
記憶によると全チャネルとmylistもです。 maoyu, osomatsusan3, 働く魔王、 etc. 

ダウンロードは失敗しないはず。コメントのみを設定で。ただ状態表示全部が同じ

**Comment by Hayao-H** [comment]
まおゆうで試してみたのですが、問題を再現できませんでした。
申し訳ありません。
v0.8.0で、データを引き継がずに実装した場合でも同じ問題が発生しますか？

**Comment by T-10001** [comment]
v0.8.0のself-containedも無印では動画取得すら失敗しまいました。１件のIDもチャネル登録も失敗しました。v0.7.1に戻ったら、登録ができるようになったが、また元の問題が発生しました。

**Comment by T-10001** [comment]
問題は一時プレイリストにのみ発生します。

**Comment by Hayao-H** [comment]
v0,8.1で問題を再現できました。
修正します。
ご不便をおかけしてしまい申し訳ありませんでした。
