### ISSUE TITLE
[バグ] v0.8.0とdevelopの動画取得が失敗する

### ISSUE THREAD

**Issue by T-10001** [Hayao-H/Niconicome#382]
**バグの説明**
v0.8.0とdevelopの動画取得が失敗する。v0.7.1では失敗しない。

**再現方法**
so20511150
sm74721

**期待する挙動**
本来ならばどのような挙動が望ましいのか

**スクリーンショット**
可能であれば

**Desktop (下記の情報の記載をお願いします):**
- OS: 最低限OSバージョン・64bitか32bitかなどをお願いします
- Version: アプリケーションのバージョン

**ログファイル**
```
プレイリスト:一時プレイリスト
sm74721の取得を開始します。
sm74721の取得に失敗しました。(詳細:視聴ページの解析に失敗しました。(サーバーエラー))
so20511150の取得を開始します。
so20511150の取得に失敗しました。(詳細:視聴ページの解析に失敗しました。(サーバーエラー))
so20511150の取得を開始します。
so20511150の取得に失敗しました。(詳細:視聴ページの解析に失敗しました。(サーバーエラー))
sm74721の取得を開始します。
sm74721の取得に失敗しました。(詳細:視聴ページの解析に失敗しました。(サーバーエラー))
```

**備考**
その他

**Comment by Hayao-H** [comment]
[PageAnalyzePlugin](https://github.com/Hayao-H/PageAnalyzePlugin)はインストールされましたか？
[こちら](https://github.com/Hayao-H/Niconicome/wiki/Niconicome%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6%E3%81%BF%E3%82%8B#%E3%82%A2%E3%83%89%E3%82%AA%E3%83%B3%E3%82%92%E3%83%80%E3%82%A6%E3%83%B3%E3%83%AD%E3%83%BC%E3%83%89%E3%81%99%E3%82%8B)のWikiも御覧ください。

**Comment by T-10001** [comment]
PageAnalyzePluginはインストールされていません。明日ためしてみます！

**Comment by T-10001** [comment]
PageAnalyzePluginインストールしたらOKでした。ありがとうございます！
