### ISSUE TITLE
[バグ] v0.8.1で動画のダウンロードができない

### ISSUE THREAD

**Issue by sh4869221b** [Hayao-H/Niconicome#391]
**バグの説明**
下記エラーが発生しています。
```詳細: ファイルの変換中にエラーが発生しました。(詳細: セグメントファイルのマージ中にエラーが発生しました。(詳細: Could not find a part of the path 'C:\Users\sh486\AppData\Local\Temp\.net\Niconicome\fvhnt5ls.5h5\tmp\sm34454474-720-2021-08-10\combined.ts'.))```

**再現方法**
sm34454474

**期待する挙動**
本来ならばどのような挙動が望ましいのか

**スクリーンショット**
可能であれば

**Desktop (下記の情報の記載をお願いします):**
 - OS: エディション	Windows 11 Pro 21H2 OS ビルド	22000.120
 - Version: 0.8.1
**ログファイル**
可能であれば添付して下さい

**備考**
その他

**Comment by Hayao-H** [comment]
ご報告ありがとうございます。
問題を確認しました。
