### ISSUE TITLE
[バグ]一部の動画でコメントをDLできない、または欠ける

### ISSUE THREAD

**Issue by Hayao-H** [Hayao-H/Niconicome#393]
**バグの説明**
明確な状況・バグの説明

**再現方法**
sm39155540、

**期待する挙動**
本来ならばどのような挙動が望ましいのか

**スクリーンショット**
可能であれば

**Desktop (下記の情報の記載をお願いします):**
 - OS:  最低限OSバージョン・64bitか32bitかなどをお願いします
 - Version: アプリケーションのバージョン

**ログファイル**
可能であれば添付して下さい

**備考**
その他

**Comment by T-10001** [comment]
sm16278191, sm16274088がDLできない

**Comment by Hayao-H** [comment]
@T-10001 
ご報告ありがとうございます。
お手数をおかけしますが、新しいIssueを立てて今一度ご報告ください。
申し訳ありません。
