### ISSUE TITLE
[バグ] 動画を取得できない 技術的詳細情報：Cannot implicitly convert type 'Microsoft.ClearScript.Undefined' to 'bool'

### ISSUE THREAD

**Issue by T-10001** [Hayao-H/Niconicome#418]
**バグの説明**
動画を取得できない

**再現方法**
so37696196
so37903088

**期待する挙動**
本来ならばどのような挙動が望ましいのか

**スクリーンショット**
可能であれば

**Desktop (下記の情報の記載をお願いします):**
- OS: Windows 10 Pro 19042.1110 64bit
- Version: v0.9.0 release

**ログファイル**
so37696196の取得を開始します。
so37696196の取得に失敗しました。(詳細:動画情報の取得中にエラーが発生しました。)
技術的詳細情報：Cannot implicitly convert type 'Microsoft.ClearScript.Undefined' to 'bool'
so37903088の取得を開始します。
so37903088の取得に失敗しました。(詳細:動画情報の取得中にエラーが発生しました。)
技術的詳細情報：Cannot implicitly convert type 'Microsoft.ClearScript.Undefined' to 'bool'

**備考**
その他

**Comment by Hayao-H** [comment]
ご報告ありがとうございます。
ここ2週間ほど私用が立て込み、対応できませんでした。
問題は解決しましたか？

**Comment by T-10001** [comment]
はい。

**Comment by Hayao-H** [comment]
ありがとうございます。
このIssueはクローズさせていただきます。
