### ISSUE TITLE
[質問] ニコニコ生放送の過去の放送のコメントDLは可能でしょうか

### ISSUE THREAD

**Issue by T-10001** [Hayao-H/Niconicome#438]
**質問の内容**
ニコニコ生放送の過去の放送のコメントDLは可能でしょうか

**Comment by Hayao-H** [comment]
ご質問ありがとうございます。
ニコ生のコメントはDLできません。
本アプリはニコニコ動画向けに開発しておりますので、今後も対応の予定はありません。
申し訳ありません。
