### ISSUE TITLE
[新機能]チャンネル情報を取得時に、視聴ページにアクセスせずに解析する

### ISSUE THREAD

**Issue by T-10001** [Hayao-H/Niconicome#448]
**バグの説明**
「ネットワーク上の動画を取得する」の機能を使ってチャネルの動画を取得するとよくすべての動画が取得しない。

**再現方法**
検証用の動画IDでも結構です

**期待する挙動**
本来ならばどのような挙動が望ましいのか

**スクリーンショット**
可能であれば

**Desktop (下記の情報の記載をお願いします):**
 - OS:  最低限OSバージョン・64bitか32bitかなどをお願いします
 - Version: アプリケーションのバージョン

**ログファイル**
可能であれば添付して下さい

**備考**
その他

**Comment by Hayao-H** [comment]
ご報告ありがとうございます
[ルパン三世 PART6](https://ch.nicovideo.jp/lupin-pt6)、[大正オトメお伽話](https://ch.nicovideo.jp/taisho-otome)などで試してみましたが、問題なく取得できました。
よろしければ、問題が発生しているチャンネルを教えていただけますか？

**Comment by T-10001** [comment]
ほとんどのチャネルに問題が発生しています。もしかすると同じチャネルで問題が発生する時もあれば発生しない時もあります。最近だと：
souleaternot １話を取得しない
hunterhunter 様々な話を取得しない
black-bullet ２話，６話を取得しない

**Comment by Hayao-H** [comment]
ご報告ありがとうございます。
@T-10001 さんが一般会員の場合、アクセス制限に引っかかっている可能性があります。
設定＞一般設定＞「動画追加時にIDのみを登録する」を有効にして再度お試しください。

**Comment by T-10001** [comment]
プレミアム会員ですが「動画追加時にIDのみを登録する」を有効にしたらhunterhunterの全動画が取得できました。取得速度も早くなりました。

ありがとうございました。

**Comment by T-10001** [comment]
タイトルがみえないのが不便ですけれども。

**Comment by Hayao-H** [comment]
ご報告ありがとうございます:bow:
タイトルや再生回数等はチャンネルページから短時間で取得できそうなので、改善します。

**Comment by T-10001** [comment]
それは朗報ですね。しかし再生数よりコメント数のほうが重要な情報ではありませんか。

**Comment by Hayao-H** [comment]
@T-10001 
ありがとうございます。
#453でコメント数・マイリスト数・再生数・サムネイルの取得も追加しました。
