### ISSUE TITLE
[バグ] ダークテーマでは「動画を検索する」の結果がみえない

### ISSUE THREAD

**Issue by T-10001** [Hayao-H/Niconicome#449]
**バグの説明**
ダークテーマでは「動画を検索する」の結果がみえない

**再現方法**
検証用の動画IDでも結構です

**期待する挙動**
本来ならばどのような挙動が望ましいのか

**スクリーンショット**
![image](https://user-images.githubusercontent.com/20717627/144166471-8f802756-8fb4-425c-9e55-5983b97eec52.png)

**Desktop (下記の情報の記載をお願いします):**
 - OS:  最低限OSバージョン・64bitか32bitかなどをお願いします
 - Version: アプリケーションのバージョン

**ログファイル**
可能であれば添付して下さい

**備考**
その他

**Comment by Hayao-H** [comment]
ご報告ありがとうございます。
問題を確認しました。
