### ISSUE TITLE
[バグ]「ダウンロード済」が認識されない。ダウンロードが完了してもすべての動画が「未ダウンロードの動画」

### ISSUE THREAD

**Issue by T-10001** [Hayao-H/Niconicome#455]
**バグの説明**
明確な状況・バグの説明

**再現方法**
検証用の動画IDでも結構です

**期待する挙動**
本来ならばどのような挙動が望ましいのか

**スクリーンショット**
可能であれば

**Desktop (下記の情報の記載をお願いします):**
 - OS:  最低限OSバージョン・64bitか32bitかなどをお願いします
 - Version: アプリケーションのバージョン

**ログファイル**
可能であれば添付して下さい

**備考**
その他

**Comment by Hayao-H** [comment]
「一時プレイリスト」ではなく、作成したプレイリストで試されていますか？

**Comment by T-10001** [comment]
はい。「一時プレイリスト」でも「作成したプレイリスト」でも問題があります。

**Comment by Hayao-H** [comment]
ご報告ありがとうございます。
問題を確認しました。
