### ISSUE TITLE
[バグ]ログインできない？(The requested address is not valid in its context. (secure.nicovideo.jp:443) @ MoveNext)

### ISSUE THREAD

**Issue by T-10001** [Hayao-H/Niconicome#457]
**バグの説明**
明確な状況・バグの説明

**再現方法**
検証用の動画IDでも結構です

**期待する挙動**
本来ならばどのような挙動が望ましいのか

**スクリーンショット**
可能であれば

**Desktop (下記の情報の記載をお願いします):**
 - OS:  最低限OSバージョン・64bitか32bitかなどをお願いします
 - Version: 0.10.0.22559

**ログファイル**
可能であれば添付して下さい

**備考**
その他

**Comment by Hayao-H** [comment]
ご報告ありがとうございます。
問題を再現できませんでした。申し訳ありません。
Webview2でログインするか、Firefoxとのcookie共有をご利用ください。

**Comment by T-10001** [comment]
問題はVPN使った時に発生。今までVPN使っても大丈夫でしたが。

**Comment by T-10001** [comment]
VPNでは動画が見えるし取得できるが、チャネル取得、ログインやダウンロードが出来ません。

**Comment by Hayao-H** [comment]
そのVPNをご利用の状態では、[ニコニコ](https://nicovideo.jp)で動画を視聴できますか？

**Comment by T-10001** [comment]
はいニコニコのサイト機能は全部正常です。niconicomeのみにエラーが出ます。しかしそれはVPNの最近のヴァージョンだけで、VPNのちょと前のヴァージョンに戻したら問題が発生しない。

**Comment by Hayao-H** [comment]
ご報告ありがとうございます。
外部ソフトが原因となる問題に関しましては、再現が難しいため現状対応できません。
大変申し訳ありません。
