### ISSUE TITLE
[バグ]一部のコメがDLできません、特にコメ数が少ない時

### ISSUE THREAD

**Issue by UmiAkai** [Hayao-H/Niconicome#468]
**バグの説明**
３０分アニメでもし1000~コメ位なら、DLしたコメ数がwebで見えたコメ数と違いがいます
コメ数多い時もあると思うけと、まだ確認していません

**再現方法**
ひだまりスケッチ特別編2　so24786870、WEBてみるコメ数が114, DLしたら毎回73。DLする項目、実験システムなどいろんな設定改変しても７３で
他の動画もこれぐらいの差があります

**期待する挙動**
全部DLですのて

ファイルは本アプリでDLしたｘｍｌと。前自分がjsonをDLしｘｍｌに転換したもの
[so24786870.zip](https://github.com/Hayao-H/Niconicome/files/8054867/so24786870.zip)

**Comment by Hayao-H** [comment]
ご報告ありがとうございます。
コメントDL機能につきましては、これからフルスクラッチで書き直す予定ですので、解決には暫く時間がかかります。
1ヶ月程度お待ち下さい。
申し訳ありません。

**Comment by Hayao-H** [comment]
## ToDo
- [ ] CommentCollectionの再実装
- [ ] CommentClientの再実装
- [ ] コメントファイルの読み書きを統合したクラス
- [ ] コメントファイルへの``<!-- BoonSutazioData=<id> -->``書き出し機能（Xeno互換）
