### ISSUE TITLE
[バグ]DL時「未処理例外（UIスレッド）」（0.11）

### ISSUE THREAD

**Issue by UmiAkai** [Hayao-H/Niconicome#490]
**バグの説明**
ダウンロードをクリック瞬間警告が表している：
![20220409203724](https://user-images.githubusercontent.com/94544030/162574452-dda4d9d8-122c-4320-be27-e9334680efb7.png)
出力に何もない

**再現方法**
ただプラグインインストールと登録済み、セッチング全部デフォルト

**Desktop (下記の情報の記載をお願いします):**
 - OS:  win10 20H2 64bit
 - Version: 0.11.0.12706

**ログファイル**
[niconicome-log-22-04-09-20-30-23.log](https://github.com/Hayao-H/Niconicome/files/8456924/niconicome-log-22-04-09-20-30-23.log)
[niconicome-log-22-04-09-20-30-59.log](https://github.com/Hayao-H/Niconicome/files/8456925/niconicome-log-22-04-09-20-30-59.log)

**備考**
試しだら-64-scと-86-scも同じく

**Comment by Hayao-H** [comment]
ご報告ありがとうございます。
問題を確認しました。
