### ISSUE TITLE
[バグ]チャンネル動画が登録できない、ダウンロードできない

### ISSUE THREAD

**Issue by KazusaTomoe** [Hayao-H/Niconicome#493]
**バグの説明**
・クリップボードの監視によりプレイリストを登録する際には登録できているが、一度Niconicomeソフトを落として再度立ち上げるとプレイリストからsoXXXXXXで始まるチャンネル動画の登録が削除されてしまう。
・soXXXXXXで始まるチャンネル動画のダウンロードができないことがある。同じチャンネル内でも発生するのでダウンロードできないチャンネル動画のすべてがストリーミング動画であるとは考えずらい。

**再現方法**
チャンネル動画をプレイリストに登録しソフトを再起動する。
soXXXXXXで始まるチャンネル動画のダウンロードができないことがある。
↓
こちらはその後ストリーミング動画以外はダウンロードできていることがわかりました。しかし、ステータス欄は「DL失敗」と表記されチェックボックスのチェックもついたままでした。

**期待する挙動**
登録したプレイリストはNiconicomeソフトを立ち下げた後もチャンネル動画は残っていて欲しい。
ストリーミング方式ではないチャンネル動画はダウンロードできて欲しい。
↓
ダウンロードできた動画については「DL失敗」と表記せずダウンロードの成功とチェックボックスのチェックを外す修正をお願いいたします。

**スクリーンショット**
可能であれば

**Desktop (下記の情報の記載をお願いします):**
 - OS:  windows10 64bit 21H2
 - Version: 0.11.0.12706

**ログファイル**
[niconicome-log-22-04-15-06-06-03.zip](https://github.com/Hayao-H/Niconicome/files/8495755/niconicome-log-22-04-15-06-06-03.zip)

**備考**

その他
いつも大変お世話になっております。
Niconicomeには大変助けられております。
大変だとは思いますがソフトの管理・アップデートのほどよろしくお願いします。

**Comment by Hayao-H** [comment]
ご報告ありがとうございます。
現在1.11.0で多くのバグが存在するようです。
大変申し訳ありませんが、修正までお待ち下さい。

**Comment by KazusaTomoe** [comment]
ご対応有り難うございました。
お忙しい中解析していただきありがとうございました。
