### ISSUE TITLE
[バグ] 動画取得後の件数が正しく表示されない

### ISSUE THREAD

**Issue by GH141421356** [Hayao-H/Niconicome#505]
**バグの説明**
動画を追加した際に出力欄に取得件数ではなく「System.Action`1[System.Collections.Generic.IEnumerable`1[Niconicome.Models.Playlist.IListVideoInfo]]件の動画を取得しました。」と表示される

**修正イメージ**
onMessage($"{videos.AddRange}件の動画を取得しました。");ではなく
onMessage($"{videos.Count}件の動画を取得しました。");だと思う

Niconicome/Models/Network/VideoIDHandler.cs
```
@@ -118,2 +118,3 @@
                 {
+                    this.FinishProcessing();
                     return AttemptResult<IEnumerable<IListVideoInfo>>.Fail("ネットワークからの動画取得に失敗しました。");
@@ -154,3 +155,3 @@
 
-            onMessage($"{videos.AddRange}件の動画を取得しました。");
+            onMessage($"{videos.Count}件の動画を取得しました。");
```

**ほかにも表示に難ありの箇所修正イメージ**
Niconicome/Models/Playlist/VideoList/VideoListContainer.cs
```
@@ -287,3 +287,3 @@
                 {
-                    return AttemptResult.Fail("{video.NiconicoId.Value}は既に現在のプレイリストに存在します。");
+                    return AttemptResult.Fail($"{video.NiconicoId.Value}は既に現在のプレイリストに存在します。");
                 }
```
Niconicome/ViewModels/Mainpage/VideoListViewmodel.cs
```
@@ -1386,4 +1386,4 @@
             if (!result.IsSucceeded || result.Data is null)
-            {
-                this.SnackbarMessageQueue.Enqueue("動画情報の取得に失敗しました");
+            {
+                this.SnackbarMessageQueue.Enqueue((String.IsNullOrEmpty(result.Message)) ? "動画情報の取得に失敗しました": result.Message);
                 return;
```

**Comment by GH141421356** [comment]
漏れていました
App Version : 0.11.1.24739
OS : Windows 10
OS Version : Microsoft Windows NT 10.0.19044.0
OS Architecture : 64bit Operating System
Process : 64bit Process

**Comment by Hayao-H** [comment]
ご報告、ご検証ありがとうございました。
問題を確認しました。
