### ISSUE TITLE
[挙動不安定] 視聴ページ解析プラグインがハンドルされない

### ISSUE THREAD

**Issue by GH141421356** [Hayao-H/Niconicome#507]
**問題の挙動の説明**
挙動１：アドオンロード、自動ログインの処理が行われない。
挙動２：アドオンロード、自動ログインは行われるが、視聴ページ解析プラグインがハンドルされず動画登録時に「視聴ページの解析に失敗しました。(ページ解析プラグイン未インストール)」エラーになる。
※両者とも出力欄に「[視聴ページ解析プラグイン]ページ解析機能の初期化が完了しました。」が出力されない。

ほぼ初期状態のDBであれば正常動作する。
動画4000件程度保存しているDBだと上記問題の挙動がおきた。

**再現方法**
マルチスレッドによるタイミングの問題かと思いますが、DBファイルサイズが大きい等（StartUpスレッドに時間がかかれば）再現するのではないでしょうか。

**期待する挙動**
アドオンロード、自動ログイン処理（StartUp.RunStartUptasksのLoadAddonAsync()以降）が安定動作すること。

**挙動考察**
StartUp内別スレッドでの初期処理よりメインスレッドのメイン画面(MainWindowViewModel)の生成が先に行われると問題の挙動が起きているように見えます。
StartUp.RunStartUptasks()にてwait LoadAddonAsync() が呼び出され、めぐりめぐってAddonHandler.InitializeAsync()内の await this._initializeAwaiterHandler.GetAwaiter(AwaiterNames.Addon); を呼び出し後 処理復帰していない。（スレッド例外も発生せず終えたような挙動：VSデバッガによる挙動）

シングルトンのオブジェクトをスレッドセーフになるように修正等試行錯誤しましたが原因はわかりませんでした。

**で、結局どうしたか：俺環用ですが**
StartUp処理(スレッド)が終了するまで、メインスレッドを止めるようにました(最大3秒)
今のところこれで安定動作しています。
```
Niconicome/Models/Local/Application/StartUp.cs
@@ -4,2 +4,3 @@
 using System.Linq;
+using System.Threading;
 using System.Threading.Tasks;
@@ -21,3 +22,4 @@
         void RunStartUptasks();
         event EventHandler? AutoLoginSucceeded;
+        AutoResetEvent StartUpEvent { get; }
     }
@@ -75,15 +76,18 @@
 
+        public AutoResetEvent StartUpEvent { get; } = new(true);
         /// <summary>
         /// スタートアップタスク
         /// </summary>
         public void RunStartUptasks()
         {
+            this.StartUpEvent.Reset();
             Task.Run(async () =>
             {
                 this.RemoveTmpFolder();
                 this.JustifyData();
                 this.DeleteInvalidFilePath();
                 await this.LoadAddonAsync();
                 await this.Autologin();
+                this.StartUpEvent.Set();
             });
         }
```
と
```
Niconicome/App.xaml.cs
@@ -67,5 +67,6 @@
         public void RunStartUpTask()
         {
             var setup = DIFactory.Provider.GetRequiredService<IStartUp>();
             setup.RunStartUptasks();
+            setup.StartUpEvent.WaitOne(3000);
         }

```

**Comment by GH141421356** [comment]
漏れていました
App Version : 0.11.1.24739
OS : Windows 10
OS Version : Microsoft Windows NT 10.0.19044.0
OS Architecture : 64bit Operating System
Process : 64bit Process

**Comment by GH141421356** [comment]
ちなみに、
setup.StartUpEvent.WaitOne(3000)
の待ちは どこでやるか
App.CreateShell()
App.OnStartup()
App.InitializeShell()
App.OnInitialized()
など 試行しましたが うまくいかず、結局 RunStartUpTask() でやることにしました。
（まぁこの対応自体 面倒になって安直な方法にしましたが・・・）

**Comment by Hayao-H** [comment]
ご報告、ご検証ありがとうございます！
アドオン系の実装は色々と複雑になってしまい、結果このような不具合が発生していると思われますので、これを期に書き直します。

**Comment by Hayao-H** [comment]
[memo] ref: #479
