### ISSUE TITLE
[バグ] ダウンロード完了したファイルカラムを右クリックし『保存フォルダで開く』を選択した際にエクスプローラーが起動展開しない

### ISSUE THREAD

**Issue by Ugya** [Hayao-H/Niconicome#513]
**バグの説明**
そのままタイトルの通りです
恐らくWindows11固有のバグだと思われますがよくわかりません

**再現方法**
sm41020109

**期待する挙動**
右クリックで『保存フォルダで開く』を選択した際にエクスプローラーが起動し、保存先フォルダを開く

**スクリーンショット**
![スクリーンショット機能の問題で薄くなってますがサンプルファイル日付欄下にあります](https://user-images.githubusercontent.com/44303852/188175600-d9c66662-6a45-4de0-8982-6327bb18f284.png)

**Desktop (下記の情報の記載をお願いします):**
 - OS:  Windows11 Pro 21H2 10.0.22000.918
 - Version: 0.11.1.24739

**Comment by Hayao-H** [comment]
おそらく #532 で修正しました。
ご迷惑をおかけしてしまい申し訳ありませんでした。
