### ISSUE TITLE
[バグ]PageAnalyzePluginの最新バージョンを使用できない

### ISSUE THREAD

**Issue by zszushi** [Hayao-H/Niconicome#523]
**バグの説明**
PageAnalyzePluginの最新バージョンを使用できない。(エラー内容は"対応していないマニフェストバージョンです。(1.1)"とのこと)

**再現方法**
PageAnalyzePluginの最新バージョンをインストールしようとする。

**期待する挙動**
インストールできるようになる。

**スクリーンショット**
![スクリーンショット 2022-12-18 125705](https://user-images.githubusercontent.com/83488055/208280569-ec3e6f11-7583-43b8-ad1f-bdacfcbd1c98.png)

**Desktop (下記の情報の記載をお願いします):**
 - OS:  Windows 10 64Bit(MacBook AirのBOOTCAMPで起動)
 - Version: 0.11.1.24739

**備考**
それでプレイリスト登録も出来ないのかもしれません。
あまり使ったことがないのでこちらの間違いだったらすみません。

**Comment by Hayao-H** [comment]
返信が遅くなってしまい申し訳ありません。
nightlyバージョン以外では[v1.3.0](https://github.com/Hayao-H/PageAnalyzePlugin/releases/tag/v1.3.0)をインストールしてください。
