### ISSUE TITLE
[質問]再起動をすると未ログイン表記になるのは正常な動作でしょうか？

### ISSUE THREAD

**Issue by TONKOTSU-UDON** [Hayao-H/Niconicome#572]
**質問の内容**
アップデート作業お疲れ様です。そして、更新していただきありがとうございます。

さて、早速0.12.0をダウンロードし、インストールいたしましたが、挙動が少し変なところがあります。まず、二段階認証が有効なせいか通常のログインができないためブラウザからログイン。ログイン完了後、再起動マークからの再起動や、バツボタンを押しソフトを終了、再び起動すると未ログインの表記になります。再びログインしようとすると、「有効なセッションがあるのでログインをスキップしますか？」と表示されログインされます。ログインはされるので大丈夫なのですが、この動作を起動毎にするのは少々不便です。これは想定された動作なのでしょうか。ご回答いただけますと幸いです。

**Comment by TONKOTSU-UDON** [comment]
大変申し訳ございません、設定にある自動ログイン設定を有効にするのを忘れておりました。しかし、パスワードによるログインができないため、機能しませんでした。自動ログインはfirefox限定の機能に変更されたのでしょうか。

**Comment by Hayao-H** [comment]
ご報告ありがとうございます。
二段階認証や連携ログインに用いているWbview2とCookieを共有する機能があったのですが、[Chromiumの仕様変更](https://gist.github.com/GramThanos/ff2c42bb961b68e7cc197d6685e06f10)によって機能しなくなっていたようです。
修正します。ご迷惑をおかけしてしまい申し訳ありませんでした。
