### ISSUE TITLE
[バグ]0.12.0にて、コメントがダウンロードされない。また、ログファイルの作成に失敗する

### ISSUE THREAD

**Issue by TONKOTSU-UDON** [Hayao-H/Niconicome#573]
**バグの説明**
連続した投稿になってしまい、大変申し訳ございません。

v0.12.0にて、動画とコメントをダウンロードしようとしたところ、コメントがほぼ全てダウンロードされずに処理が終了してしまいます。最近投稿されたものと少し前の動画の2つにて検証いたしましたが、どちらもほぼダウンロードされることなく処理が終了してしまいます。

試験的なコメント取得システムを有効にした場合は、コメント自体のダウンロードは行われますが非常に数が少なく、全てのコメントがダウンロードされません。

動画はしっかりと綺麗にダウンロードしてくれます。

**再現方法**
検証に使用した動画はこちらです。
sm41958959
sm41282319

**期待する挙動**
コメントが正常にダウンロードされる。

**スクリーンショット**
元動画は4032コメントです。

試験的なコメント取得 **無効**
![スクリーンショット 2023-04-01 061926](https://user-images.githubusercontent.com/95231657/229233730-c3c2728e-88b2-4891-852f-bfe9abc9c658.png)

試験的なコメント取得 **有効**
![スクリーンショット 2023-04-01 061920](https://user-images.githubusercontent.com/95231657/229233761-6c725580-af2a-459c-a61d-76e8d45c91e1.png)

ダウンロード設定
![スクリーンショット 2023-04-01 062655](https://user-images.githubusercontent.com/95231657/229234712-6182904f-8948-4a06-9d9b-af758874c3c8.png)

**Desktop (下記の情報の記載をお願いします):**
 - OS:  windows10home  64bit 10.0.19045 ビルド 19045
 - Version: niconicome-win-x64-v0.12.0

**ログファイル**
![スクリーンショット 2023-04-01 061753](https://user-images.githubusercontent.com/95231657/229233041-fbc214c2-7996-4a04-8fff-5278e97a34c3.png)

検証中に一つ作成されました。
[niconicome-log-23-04-01-06-18-36.log](https://github.com/Hayao-H/Niconicome/files/11127005/niconicome-log-23-04-01-06-18-36.log)

**備考**
その他

**Comment by Hayao-H** [comment]
ご報告ありがとうございます。
問題を確認しました。
dupe: #559

**Comment by Hayao-H** [comment]
Duplicate of #559
