### ISSUE TITLE
[バグ] データベース作成異常

### ISSUE THREAD

**Issue by Ugya** [Hayao-H/Niconicome#586]
**バグの説明**
起動し、ログインしてメインウィンドウまでは立ち上がるが、ログファイルの内容が「データベースファイルのオープンに失敗しました。」となり、「[228-1]サーバーの実行中に例外が発生しました。」のログ吐きがいつまで経っても止まらずにアプリを何らかの形で終了させるまでログが元気にモリモリと成長する。
それを無視して動画IDを登録しようとすると「プレイリストが選択されていない状態で動画リストの更新を試行しました。」と出て積む。

**再現方法**
[メドレー「ゲッターアイドル（仮）」](https://www.nicovideo.jp/watch/sm42179886)

**期待する挙動**
DB生成がスムーズに終了し、動画IDを登録するとリストに登録されて動画ダウンロードスタンバイまでされ、サーバ側にある最大画質の動画取得が出来ること。

**スクリーンショット**
![スクリーンショット](https://user-images.githubusercontent.com/44303852/236689859-0310f39a-b088-41ee-8014-e9571066fdbd.jpg)
![元気なログファイル](https://user-images.githubusercontent.com/44303852/236689186-93af8476-a046-4499-9eb9-0ef34e37ea61.jpg)

完全クリーン環境下での成功例(こうなって欲しかった)
![完全クリーン環境下での成功例](https://user-images.githubusercontent.com/44303852/236689983-00b7b328-6794-463c-8ba6-2c0dd97d00f7.jpg)

**Desktop (下記の情報の記載をお願いします):**
 - OS:  Windows 11 Pro 22H2 22621.1635
 - Version: 0.12.1.8374 / ffmpeg , ffprobe - Latest Auto-Build (2023-05-07 12:46)
**ログファイル**
[niconicome-log-23-05-08-01-12-34.log](https://github.com/Hayao-H/Niconicome/files/11415457/niconicome-log-23-05-08-01-12-34.log)

**備考**
スクリーンショット下記の完全クリーン環境下でも異常環境下と同様内容のログで、終了するまでサイズ肥大化が止まらず。

**Comment by Ugya** [comment]
データログ肥大化は起動して通信、指定フォルダ内動画やコメントに対するディスクアクセスを行なわない時だけ発生し、そういった行為を行なうとそちらの動作ログに置き換わるようです…
と思い再現調査をしたのですが、全く再現しないため困惑中。

![タイトルなし](https://github.com/Hayao-H/Niconicome/assets/44303852/a73bcc32-8182-4ff3-8050-b84757b9c912)
5/9時点での別組で設定した完全クリーン環境下での動作ログ
[niconicome-log-23-05-09-23-01-41.log](https://github.com/Hayao-H/Niconicome/files/11431983/niconicome-log-23-05-09-23-01-41.log)
[settings.json](https://github.com/Hayao-H/Niconicome/files/11432009/settings.json.txt)

**Comment by Ugya** [comment]
完全ではないのですが、再現できたっぽいので症状の解説を付けます。

何らかの理由でniconicomeが異常動作にてクラッシュしてしまい、再度アプリを起動した時に左カラムの『プレイリスト一覧』が表示されなくなったら異常ログを延々と吐くようです。
バックアップを取ってなければ\addonsフォルダを削除の上、上書き初期化が必要で手が出せません。
※何らかの理由の例：
①tsファイルマージに失敗した
②tsファイルのダウンロードに失敗した

**再現方法**
例①対応分
[完璧で究極のアイドル陰陽師美食屋ゲッター　～アフォナー電機を添えて～](https://www.nicovideo.jp/watch/sm42183262)
[niconicome-log-23-05-11-13-54-07.log](https://github.com/Hayao-H/Niconicome/files/11508697/niconicome-log-23-05-11-13-54-07.log)
例②対応分
[紆余曲折あっても君は完璧で究極のゲッター](https://www.nicovideo.jp/watch/sm42217578)
[niconicome-log-23-05-18-03-31-21.log](https://github.com/Hayao-H/Niconicome/files/11508698/niconicome-log-23-05-18-03-31-21.log)
[niconicome-log-23-05-18-03-32-22.log](https://github.com/Hayao-H/Niconicome/files/11508789/niconicome-log-23-05-18-03-32-22.log)
[niconicome-log-23-05-18-03-33-06.log](https://github.com/Hayao-H/Niconicome/files/11508795/niconicome-log-23-05-18-03-33-06.log)
上書き初期化後
[niconicome-log-23-05-18-03-38-27.log](https://github.com/Hayao-H/Niconicome/files/11508798/niconicome-log-23-05-18-03-38-27.log)

**Comment by Hayao-H** [comment]
ご報告ありがとうございました。
#589 にて修正しました。
