### ISSUE TITLE
[質問] 【上級者向け】コレクション1ブロックあたりのコメント数（推奨値：100）を変えるとどの違いがありますか

### ISSUE THREAD

**Issue by T-10001** [Hayao-H/Niconicome#587]
**質問の内容**
【上級者向け】コレクション1ブロックあたりのコメント数（推奨値：100）の値を変えるとどの違いがありますか。

どの値だともとも多くのコメントが取得できあますか。

**Comment by Hayao-H** [comment]
こちらをご参照ください
[Niconicome wiki | コメントコレクション](https://github.com/Hayao-H/Niconicome/wiki/%E7%94%A8%E8%AA%9E%E8%A7%A3%E8%AA%AC#%E3%82%B3%E3%83%A1%E3%83%B3%E3%83%88%E3%82%B3%E3%83%AC%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3)
