### ISSUE TITLE
5chスレからの移行願い

### ISSUE THREAD

**Issue by JiroYama** [Hayao-H/Niconicome#590]
いつもアプリを便利に利用させていただいております。
アプリの内容とは全く無関係なお話で恐縮ですが、現在の5chのスレッドをどこか別の掲示板
（したらば等）に移行をお願いすることはできないでしょうか。
最近の5chは規制が多いようで、その巻き込みで一切投稿できない状態が長らく続いており、
なかなか質問も感謝をお伝えすることもできず頭を抱えておりました。
もし可能であれば別の掲示板への移行をご検討いただけたらと存じます、お忙しい中を本当にすみません。

**Comment by Hayao-H** [comment]
ご要望ありがとございます。また、返信が遅くなりまして申し訳ないです。
現状、作者へのコンタクト方法としては
匿名
- 5ch
- マシュマロ
要アカウント
- Twitter
- Slack
- Github
があるかと思います。
個人の考えとしましては、人口の多い5chとTwitterはフォーラムとして残しておきたいと思っております。ただ、5chの規制に関しては自分も多々巻き込まれることがあるので、承知しております。その際は、お手数をお掛けしますが、他のコンタクト方法をお使いいただくか、回線を変えるなどして書き込みいただきたいです…スミマセン😢

感謝のお気持ち、大変ありがたいです！
何か他に対応できることがあればお知らせください。
