### ISSUE TITLE
[新機能]動画情報の取得をAPIに切り替える

### ISSUE THREAD

**Issue by Hayao-H** [Hayao-H/Niconicome#600]
**この要望は何らかの問題に起因するものですか？**
HTMLの解析よりも非公式APIの方が安定する？

**どのようなご要望ですか？**
具体的な説明をお願いします

**ご要望を実現することが出来なかった場合、受け入れ可能な代替案はありますか？**
具体的な説明をお願いします

**備考**

**Comment by Hayao-H** [comment]
ご報告ありがとうございます。
``https://www.nicovideo.jp/api/watch/v3``の利用を考えていました。
このAPIはPC版ニコニコ動画の視聴ページで連続再生等、ページを切り替えないSPA的な動作をする際に利用されているかと思われます。

**Comment by nnn-revo2012** [comment]
>https://www.nicovideo.jp/api/watch/v3の利用を考えていました
動画情報ってそっちの方ですか。ちょい勘違いしてました。失礼いたしました。
