### ISSUE TITLE
全過去ログをドウンロード可能になる

### ISSUE THREAD

**Issue by T-10001** [Hayao-H/Niconicome#63]
**この要望は何らかの問題に起因するものですか？**
例: 全過去ログがドウンロードできません。一部コメントしかできません。例えばsm3693445の動画に37000ぐらいのコメントがあるが10000ぐらいしかドウンロードできません。

**どのようなご要望ですか？**
全過去ログをドウンロード可能になる。sm3693445の場合は全３７０００～のコメント

**ご要望を実現することが出来なかった場合、受け入れ可能な代替案はありますか？**
全過去ログをドウンロード可能にする方法を教えて下さい

**Additional context**

**Comment by Hayao-H** [comment]
[sm3693445](https://nico.ms/sm3693445)について手元の環境(Win10 x64 19042)で確認したところご指摘の問題が再現しました。
現在原因を究明中です。
ご迷惑をおかけして申し訳ありません。

**Comment by Hayao-H** [comment]
原因が判明しました。
本ソフトは過去ログをDLする際に、
1. サーバー(nmsg.nicovide.jp)からコメントを取得する
2. 取得したコメントの中で一番古いもの(C(0))を探す
3. C(0)の投稿日時の1ms以前に投稿されたコメントを取得する

という動作を繰り返しております。
しかし、サーバーから返されるコメントは新しいものから順になっているのではなく、極端に古いコメントが混入していることもあるようです。
したがって、過去ログ探索のロジックが狂い、このようなバグが発生した模様です。
すでに修正は完了しましたので修正したコードを次回のGAで統合します。
@T-10001 さんご協力ありがとうございました。

**Comment by T-10001** [comment]
修正したコードをすぐにでもpushできますか。こちらでbuildしたいので。

**Comment by Hayao-H** [comment]
コードはmainブランチではなくdevelopブランチにすでにpushしています。
``git clone``した後、developブランチをcheckoutしてください。
dotnet sdkがインストールされている場合、``dotnet publish {options}``でexeファイルを出力できます。
ridやself-contained、publish-single-file等のオプションはご自身で指定してください。
よろしくお願いします。

**Comment by T-10001** [comment]
sm3693445に修正したコードを試した。しかしドウンロードしたコメント数は37,716ではなく37327でした（Notepad++で「</chat>」の数をcount機能で数えて）。そのほかの37716-37327=389のコメントはなぜないでしょうか。

**Comment by Hayao-H** [comment]
コメントのオフセットを調節する機能を追加しました。
お手数をおかけしますがdevelopブランチを``pull``してもう一度ビルドしてください。

設定(歯車のアイコン)=>「ダウンロード設定」=>「コメントのオフセット」を任意の数に設定してください。
200に設定すると、37515コメントを取得できました。

![setting](https://user-images.githubusercontent.com/55943986/110231202-8380b800-7f59-11eb-9ee5-3cb7f87c93bb.png)
この数字は大きくすると漏れなく取得できますが、その分速度が小さくなります。

また、ニコニコの視聴ページを確認したところ、この動画の最新コメント番号は37515となっていました。
実際には37716コメントも存在しないようです。したがって、私は全てのコメントを取得できているのではないかと思います。

![Screenshot_2021-03-07 ウサ＆ネコ](https://user-images.githubusercontent.com/55943986/110231347-9a73da00-7f5a-11eb-901a-5a092c014ffc.png)

---
You seems not to be a native Japanese speaker.
Shall I respond in English?
My English skill is very poor... but I'll try to do my best. （間違っていたらスミマセン）

**Comment by T-10001** [comment]
It is true that I am not a native Japanese speaker. If your English skill is very poor, I think it would be better to use Japanese.

確かに一番高い数字のコメ番は37517ですね。

sm3693445でオフセットオプションを試してみました。ご覧の結果です：
＠999999 --> 705 `</chat>` 数
@200 --> 37482 `</chat>` 数
@180 --> 37403 `</chat>` 数
@0 --> 705 `</chat>` 数

ドウンロードしたXMLファイルをTXTとしてアタッチしました：

[[sm3693445]ウサ＆ネコoffset=200.txt](https://github.com/Hayao-H/Niconicome/files/6096730/sm3693445.offset.200.txt)
[[sm3693445]ウサ＆ネコoffset=0.txt](https://github.com/Hayao-H/Niconicome/files/6096728/sm3693445.offset.0.txt)
[[sm3693445]ウサ＆ネコoffset=180.txt](https://github.com/Hayao-H/Niconicome/files/6096729/sm3693445.offset.180.txt)
[[sm3693445]ウサ＆ネコoffset=999999.txt](https://github.com/Hayao-H/Niconicome/files/6096727/sm3693445.offset.999999.txt)

**Comment by Hayao-H** [comment]
@T-10001 
Thanks for your consideration. Please forgive me for using Japanese.

``offset=180``・``offset=200``の場合ともに、一番大きいコメ番は37517のようですね。
これ以上網羅的にコメントを取得する手段を思いつくことができないので、過去ログ機能については今の状態で一旦完成ということでよろしいでしょうか？

**Comment by T-10001** [comment]
この公式動画（so38080161）はどうでしょうか。offset=200を使ったところやく5700/35000コメントが取得されました。XMLファイルから見るに何故かコメ版1900~6200、11000~15000、18000~21000、23000-28000が穴みたいに欠落している。offset=600を使ったらドウンロードが失敗しました。

何らかの手がかりになりませんでしょうか。

そして一番良いオフセット数値はどう決めますか。

**Comment by Hayao-H** [comment]
無職転生のページでブラウザーの開発者ツールを眺めていたところ、古いコメントが混入する原因に気づきました。
おそらく[ニコる](https://dic.nicovideo.jp/a/%E3%83%8B%E3%82%B3%E3%82%8B)が原因です。
現在対処中です。これで根本的な解決ができると思います。
