### ISSUE TITLE
[バグ] 初回動画ダウンロード時、"No such file or directory"エラーによりffmpegの実行に失敗する。(おま環？)

### ISSUE THREAD

**Issue by TONKOTSU-UDON** [Hayao-H/Niconicome#634]
**バグの説明**
初回動画ダウンロード時、保存先に指定しているディレクトリにダウンロードしている動画のフォルダが生成されず、ffmpegの実行に失敗し動画がダウンロードできない。

なお、コメント、サムネイル画像など動画以外のものをダウンロードした際はフォルダが生成され保存される。その後動画の再度ダウンロードを試みるとフォルダが生成されているためffmpegが実行され正常に完了する。
また、たまに一時プレイリストから動画を削除できなくなる。

**再現方法**
こちらの三つの動画で検証
[sm42661297](https://www.nicovideo.jp/watch/sm42661297)
[sm42308476](https://www.nicovideo.jp/watch/sm42308476)
[sm42661336](https://www.nicovideo.jp/watch/sm42661336)

**期待する挙動**
保存先ディレクトリに指定されている階層にフォルダが生成される。

**スクリーンショット**
![image](https://github.com/Hayao-H/Niconicome/assets/95231657/8f9ddf26-f74d-482f-8761-554cfd9f8d48)

![image](https://github.com/Hayao-H/Niconicome/assets/95231657/278fb48b-9242-4a84-9793-bd889aaab523)

フォルダが生成されていない(sm42661336)
![image](https://github.com/Hayao-H/Niconicome/assets/95231657/16dde5b7-f9c0-4a68-979f-3643cfb56ffb)

**Desktop (下記の情報の記載をお願いします):**
 - OS:  windows10 64bit
 - Version: Niconicome - 0.13.3.5565 API - 1.4.0

**ログファイル**
[niconicome-log-23-10-06-22-18-39.log](https://github.com/Hayao-H/Niconicome/files/12831565/niconicome-log-23-10-06-22-18-39.log)

別のログファイルを見たらこのようなエラーも出ていました。
```
[22:13.37][error][21-13]　[v2_video]テーブルには更新対象となるID10のレコードが存在しません。
[22:13.55][error][21-14]　指定されたレコードが存在しません。
[22:14.03][error][21-13]　[v2_video]テーブルには更新対象となるID10のレコードが存在しません。
[22:14.06][error][21-14]　指定されたレコードが存在しません。
[22:14.15][error][21-14]　指定されたレコードが存在しません。
```

**備考**
階層が複雑なのでおま環の可能性が非常に高く、回避方法も存在するため重要度は低めかもしれません。

**Comment by Hayao-H** [comment]
ご報告ありがとうございます。
問題を確認しました。
