### ISSUE TITLE
[バグ] Cookie情報が正しくないと視聴ページの解析に失敗する

### ISSUE THREAD

**Issue by Ugya** [Hayao-H/Niconicome#642]
**バグの説明**
niconicomeが未起動時でログイン中(Webview2+Cookie)にEdgeのCookieを削除するとniconicomeでは見た目のログイン状態は保持されているが、動画IDもしくはURLを貼り付けると「(視聴ページ解析プラグイン)視聴ページの解析に失敗しました。(詳細:APIへのアクセスに失敗しました。(status:400))」というエラーが出てプレイリストに登録できない
なお、niconicome側からログアウトし、ブラウザログインをし直すと正常に戻り、リストに登録できるようになり、その後の動作も問題はなし

**再現方法**
[除夜m@s'23 なんどでも除夜ろう](https://www.nicovideo.jp/watch/sm43216479)

**期待する挙動**
実際に通信を行なってCookieと突合した際にエラーが出るようであれば再ログインを促す

**Desktop (下記の情報の記載をお願いします):**
 - OS:  Windows 11 Pro  23H2 22631.2861
 - Version: 0.13.3.5565 / 1.4.0

**ログファイル**
[niconicome-log-23-12-31-20-58-27.log](https://github.com/Hayao-H/Niconicome/files/13801140/niconicome-log-23-12-31-20-58-27.log)

**Comment by Hayao-H** [comment]
#647 で対応します。
