### ISSUE TITLE
[バグ] 一部のdアニメストアの動画コメントがDLできない

### ISSUE THREAD

**Issue by T-10001** [Hayao-H/Niconicome#643]
**バグの説明**
一部のdアニメストアの動画コメントがDLできない
例えば：
https://www.nicovideo.jp/series/96209
so42970353
so42851510

**再現方法**
検証用の動画IDでも結構です

**期待する挙動**
本来ならばどのような挙動が望ましいのか

**スクリーンショット**
可能であれば

**Desktop (下記の情報の記載をお願いします):**
 - OS:  Windows 10 Pro 64bit 21H2 19044.1645
 - Version: 0.13.3.23751

**ログファイル**
```
[System]動画のダウンロードを開始します。(2件)
[System]so42970353のダウンロード処理を開始しました。
[System]クリップボードに情報をコピーしました。
[System]so42970353のダウンロード処理に失敗しました。
[System]詳細：None
[System]so42851510のダウンロード処理を開始しました。
[System]so42851510のダウンロード処理に失敗しました。
[System]詳細：コメント取得でエラーが発生しました。(詳細：Index was outside the bounds of the array.)
[System]so42970353ほか1件の動画をダウンロードしました。
```

**備考**
その他

**Comment by Hayao-H** [comment]
fixed in #657

**Comment by T-10001** [comment]
すみません。
ご覧のｄアニメストア動画のコメントはまだDLできません。

so41675697
so41613027
so41874877
so42717603
so42683632
so42653107
so42806594
so42762753

logファイル：
[niconicome-log-24-09-23-14-11-16.log](https://github.com/user-attachments/files/17092703/niconicome-log-24-09-23-14-11-16.log)
