### ISSUE TITLE
[バグ]　ダウンロードボタンをクリックするとBlazorの読み込みエラーが発生します

### ISSUE THREAD

**Issue by T-10001** [Hayao-H/Niconicome#655]
**バグの説明**
明確な状況・バグの説明
動画のチェックボックスをチェックしてダウンロードボタンをクリックするとBlazorの読み込みエラーが発生します。ダウンロードが実行しません。

動画のチェックボックスをチェックにしたあと、チュックをクリアしてダウンロードボタンをクリックするとダウンロードがせいこうします。

**再現方法**
検証用の動画IDでも結構です

**期待する挙動**
本来ならばどのような挙動が望ましいのか
エラーが発生しない

**スクリーンショット**
可能であれば

**Desktop (下記の情報の記載をお願いします):**
OS: Windows 10 Pro 64bit 22H2　19045.4412
Version: 0.14.0.28768

**ログファイル**
可能であれば添付して下さい

**備考**
その他

**Comment by Hayao-H** [comment]
ご報告ありがとうございます。
こちら、 #654 で修正いたしました。
