### ISSUE TITLE
消された動画のコメントをドウンロードできるようになる機能

### ISSUE THREAD

**Issue by T-10001** [Hayao-H/Niconicome#69]
**この要望は何らかの問題に起因するものですか？**
消された動画のコメントをドウンロードできません。ID登録の時点でしっぱいします

**どのようなご要望ですか？**
消された動画のコメントをドウンロードできる機能

**ご要望を実現することが出来なかった場合、受け入れ可能な代替案はありますか？**
具体的な説明をお願いします

**Additional context**

**Comment by Hayao-H** [comment]
非ログイン状態で削除動画の視聴ページに直接アクセスすると``404 NotFound``がサーバーから返されるようです。
例えば、[sm19824480](https://www.nicovideo.jp/watch/sm19824480)をログインせずにFirefox86で直接開いたところ、
下のような画面が表示されました。

<img src="https://user-images.githubusercontent.com/55943986/110233943-e169cb80-7f6a-11eb-8ce6-3f422bf479d2.png"  width="600"/>

プログラムからアクセスした場合にもこれと同じ現象が起こっているようです。
現在削除された動画のダウンロードについて修正中です。

**Comment by Hayao-H** [comment]
developに``push``しました。
>削除動画の動画をダウンロードすると[Fooさんの桜ノ雨](https://nico.ms/sm38213757)がダウンロードされます。

**Comment by T-10001** [comment]
ありがとうございました！

**Comment by T-10001** [comment]
チャンネルが閉鎖した動画のコメントはまだドウンロードできませんが、そんなコメントもドウンロードできるようにするが可能ですか。例えば[らいむいろ戦奇譚(公式)](https://www.nicovideo.jp/user/1524165/mylist/26630362)の[so15131210](https://www.nicovideo.jp/watch/so15131210)
