### ISSUE TITLE
[バグ]詳細: コメントの取得に失敗しました。(詳細:DefaultPostTargetが見つかりません。)

### ISSUE THREAD

**Issue by T-10001** [Hayao-H/Niconicome#95]
**バグの説明**
コメントをドウンロードしようとしたらコメントの取得に失敗しました

出力ログから：
```
1件の動画を追加します。
so38359917の動画情報を取得中です...(1/1)
so38359917を追加しました。(1/1)
動画の追加処理が完了しました。(1件)
---------------------------------------------------
動画のダウンロードを開始します。(1件)
so38359917のダウンロード処理を開始しました。
so38359917のダウンロードに失敗しました。
詳細: コメントの取得に失敗しました。(詳細:DefaultPostTargetが見つかりません。)
ダウンロード出来ませんでした。
```

**再現方法**
so38359917を登録してドウンロードを開始する

**期待する挙動**
本来ならばドウンロードが失敗しない

**スクリーンショット**
可能であれば

**Desktop (please complete the following information):**
 - OS:  Windows 10 Pro 19042.746 64bit
 - Version: 0.2

**ログファイル**
[niconicome-log-21-03-15-15-42-32.log](https://github.com/Hayao-H/Niconicome/files/6139010/niconicome-log-21-03-15-15-42-32.log)

**Comment by Hayao-H** [comment]
本日ニコニコが実施したアップデートで、大幅な変更があったようです。
現在修正が完了し、この後修正したコードを``main``/``develop``ブランチにマージします。

**Comment by T-10001** [comment]
developと0.22使っても公式動画（so38359917など）のコメントは取得されない、ただのブランクファイルを作成する：

```
<packet>
<thread resultcode="0" thread="" server_time="0" last_res="0" revision="0"/>
</packet>
```

**Comment by Hayao-H** [comment]
確認しました
申し訳ありません
現在修正中です

**Comment by Hayao-H** [comment]
修正したコードを``develop``に``push``しました。

**Comment by T-10001** [comment]
developと0.2.3をてめした。有料動画のコメントはまだDＬできません。

**Comment by Hayao-H** [comment]
有料動画の場合、``userID``が``null``になるためコメントを取得できていなかったようです。
現在修正中です。
申し訳ありません。

**Comment by Hayao-H** [comment]
``develop``に``push``しました。
