### ISSUE TITLE
[バグ] v0.2.2においてニコニコ動画仕様変更後、動画がダウンロードができない

### ISSUE THREAD

**Issue by Ugya** [Hayao-H/Niconicome#99]
**バグの説明**
2021年3月16日適応のニコニコ動画仕様変更において動画のダウンロードが不能

**再現方法**
so38408085及びsm9

**期待する挙動**
sm9の動画データがダウンロードできること

**Desktop (please complete the following information):**
 - OS:  Windows10 x64 20H2 Build 19041.vb_release.191206-1406
 - Version: v0.2.2

**ログファイル**
Niconicomeログ
App Version : 0.2.2.41390
App Path : 省略\niconicome\Niconicome.exe
OS : Windows 10
OS Version : Microsoft Windows NT 10.0.19042.0
Date : 21/03/16 21:23:38
---------------------------------------------------

[21:23.38][Error] セッションの確立に失敗しました。
Niconicomeエラー情報
---------------------------------------------------
Exception Message : DMCサーバーへのPOSTに失敗しました。(status: 403, reason_phrase: Forbidden)
Exception Type : HttpRequestException
Stack Trace :
   at Niconicome.Models.Domain.Niconico.Watch.DmcDataHandler.GetSessionInfoAsync(DmcPostData dmcPostData)
   at Niconicome.Models.Domain.Niconico.Watch.WatchSession.EnsureSessionAsync(String nicoId, Boolean isVideoDownload)
---------------------------------------------------

**備考**
ニコニコ動画関連ツール総合スレ part8 
http://egg.5ch.net/test/read.cgi/software/1613800388/252,279

**Comment by Hayao-H** [comment]
このバグに関して修正が完了したので``hotfix``ブランチを``develop``と``main``にマージしてリリースします。
ご協力ありがとうございました。

**Comment by Hayao-H** [comment]
技術的な説明を一応...
ニコニコで視聴セッションを確立するためは、``api.dmc.nico``（所謂DMC鯖）に必要なデータをPOSTする必要があるのですが、
その際のパラメーターの一つである``transferPriset``がプレミアム会員の場合ある固定値を取っていました。
私はそれを見て全ての場合においてその固定値を送信するようにコードしていたのですが、実際にはプレミアム・一般で値が違っていたようです。
今回の``403 Forbidden``はこれが原因のようです。
ご迷惑をおかけいたしました。
